# M.A.D. Python Libraries - `numpy`

<span style="color:red;">**M.A.D.** => **M**achine **L**earning and **D**ata Science<span>

**Purpose:** The purpose of this workbook is to help you get comfortable with the topics outlined below.

**Prereqs**
* None
    
**Recomended Usage**
* Run each of the cells (Shift+Enter) and edit them as necessary to solidify your understanding
* Do any of the exercises that are relevant to helping you understand the material

**Topics Covered**
* Numpy

# Workbook Setup

## Troubleshooting Tips

If you run into issues running any of the code in this notebook, check your version of Jupyter, Python, extensions, libraries, etc.

```bash
!jupyter --version

jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : not installed
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.2.3
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.3
```

```bash
!jupyter-labextension list

JupyterLab v1.2.3
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @aquirdturtle/collapsible_headings v0.5.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        @jupyterlab/git v0.8.2  enabled  OK
        @jupyterlab/github v1.0.1  enabled  OK
        jupyterlab-flake8 v0.4.0  enabled  OK

Uninstalled core extensions:
    @jupyterlab/github
    jupyterlab-flake8
```

In [6]:
# # Run this cell to check the version of Jupyter you are running
# !jupyter --version

In [2]:
# # Run one of these cells to check what extensions you are using
# !jupyter-labextension list
# !jupyter-nbextension list

In [1]:
# # Check ipython version
# import sys
# print(sys.version)

## Notebook Configs

In [1]:
# AUTO GENERATED CELL FOR NOTEBOOK SETUP

# NOTEBOOK WIDE MAGICS

# Reload all modules before executing a new line
%load_ext autoreload
%autoreload 2

# Abide by PEP8 code style
%load_ext pycodestyle_magic
%pycodestyle_on

# LIBRARY SPECIFIC MAGICS - UNCOMMENT AS NEEDED

# Plot all matplotlib plots in output cell and save on close
%matplotlib inline

In [1]:
import numpy as np

In [3]:
def print_a(a):
    print('Shape: {}'.format(a.shape))
    print(a)

# [`numpy`](https://docs.scipy.org/doc/numpy/reference/)

`numpy` (numerical Python) is a widely used library for data representation and manipulation (written in C). 

[Numpy Cheatsheet (pdf)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

## Creating Arrays

```python
np.array()
```

#### Create arrays from lists

```python
np.array()
```

In [22]:
a = np.array([1, 2, 3])
print_a(a)

Shape: (3,)
[1 2 3]


In [23]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
print_a(b)

Shape: (2, 3)
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [24]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)
print_a(c)

Shape: (2, 2, 3)
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


We can also create arrays with initial placeholders of datetimes, random numbers, ones, zeros, evenly spaced values, grids, etc. Numpy gives us support for all of these common use cases.

#### Create arrays of constant numbers

```python
np.zeros()
np.ones()
np.full()
```

In [27]:
# Create an array of zeros with shape 3 by 4
a = np.zeros((3, 4))
print_a(a)

Shape: (3, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
# Create an array of ones with shape 2 x 3 x 4
a = np.ones((2, 3, 4), dtype=np.int16)
print_a(a)

Shape: (2, 3, 4)
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [40]:
# Create a constant array of 7s
e = np.full((2, 2), 7)
print_a(e)

Shape: (2, 2)
[[7 7]
 [7 7]]


#### Create arrays of random numbers

```python
np.random.random()
```

In [52]:
# Create a 2x2 array with random values (defaults to random nums b/t 0 and 1)
a = np.random.random((2, 2))
print_a(a)

Shape: (2, 2)
[[0.12699216 0.36911603]
 [0.29257144 0.7664831 ]]


In [58]:
# Create a 2x3x4 array with random values
a = np.random.rand(2, 3, 4)
print_a(a)

Shape: (2, 3, 4)
[[[0.28051645 0.96704531 0.82092445 0.46193141]
  [0.6174535  0.05172732 0.80286199 0.72452067]
  [0.45590498 0.25790384 0.30292671 0.01939364]]

 [[0.72827542 0.01308376 0.83031978 0.6420565 ]
  [0.02498747 0.370077   0.96324986 0.10412153]
  [0.34407766 0.57707586 0.98575563 0.92611013]]]


In [60]:
# Create an array with random ints
a = np.random.randint(-3, 3, size=12)
print_a(a)

Shape: (12,)
[ 0  2  2 -1 -2 -3  2 -3 -2  0  2  0]


In [66]:
# Create uniform distribution between 0 and 1 in a 2x4 matrix
a = np.random.random_sample((2, 4))
print_a(a)

Shape: (2, 4)
[[0.6171063  0.05290367 0.11975113 0.68710523]
 [0.84516373 0.67981585 0.75594438 0.90401364]]


#### Create empty arrays
```python
np.empty()
```

In [20]:
np.empty((3,2)) #=>Create an empty array (uninitialized so whatever is in mem loc already stays)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

#### Create evenly spaced arrays

```python
np.arange()  # start, stop, step
np.linspace()  # start, stop, num quantities
```

Whats the difference?
* `linspace` enables you to control the precise end value
* `arange` gives you more direct control over the increments between values

In [30]:
# Create an array of evenly spaced values (step value)
# from 10 to 25 in steps of 5
d = np.arange(10, 25, 5)
print_a(d)

Shape: (3,)
[10 15 20]


In [38]:
# Create an array of evenly spaced values (number of samples)
# 9 numbers from 0 to 2
print_a(np.linspace(0, 2, 9))

Shape: (9,)
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


#### Create an identity matrix

```python
np.eye()
```

In [11]:
f = np.eye(2); f #=>Create a 2X2 identity matrix

array([[1., 0.],
       [0., 1.]])

#### Create a mesh grid

```python
np.mgrid()
```

In [49]:
# Create a 2 meshgrids with nums from 0 to 5
x, y = np.mgrid[0:5, 0:5]
print_a(x)
print_a(y)

Shape: (5, 5)
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
Shape: (5, 5)
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [50]:
# Create a meshgrid from -1 to 1 with 5 numbers
x = np.mgrid[-1:1:5j]
print_a(x)

Shape: (5,)
[-1.  -0.5  0.   0.5  1. ]


## I/O

```python
np.save()
np.load()
np.savez()
```

### Saving and Loading on Disk

Save an array as a .npy file

In [67]:
np.save('my_array', a)

In [25]:
np.load('my_array.npy')

array([1, 2, 3])

Save several arrays in an uncompressed .npz file

In [68]:
np.savez('array.npz', array1=a, array2=b)

In [33]:
my_arrays = np.load('array.npz')

In [34]:
my_arrays['array1']

array([1, 2, 3])

### Saving and Loading Text Files

We can also load data from text file (each row must have same # of vals)

In [ ]:
np.loadtxt("myfile.txt")

Or load data from a text file with missing values handled in a specific way

In [ ]:
np.genfromtxt("my_file.csv", delimiter=',')

In [ ]:
np.savetxt("myarray.txt", a, delimiter=" ")

## Datatypes

```python
np.int64, np.float32, np.complex, np.bool, np.object, np.string_, np.unicode_
```

In [70]:
np.int64  # Signed 64-bit integer type

numpy.int64

In [71]:
np.float32  # Standard double-precision floating point

numpy.float32

In [72]:
np.complex  # Complex numbers represented by 128 floats

complex

In [73]:
np.bool  # Boolean type storing TRUE and FALSE values

bool

In [74]:
np.object  # Python object type

object

In [75]:
np.string_  # Fixed-length string type

numpy.bytes_

In [76]:
np.unicode_  # Fixed-length unicode type

numpy.str_

## Inspecting Your Array

```python
my_array.shape  # array shape
my_array.ndim  # num dimensions
my_array.size  # num elements
len(my_array)  # array length
my_array.astype(int)  # convert type
```

In [77]:
print(a)
a.shape  # Array dimensions

[[0.6171063  0.05290367 0.11975113 0.68710523]
 [0.84516373 0.67981585 0.75594438 0.90401364]]


(2, 4)

In [78]:
len(a)  # Length of array

2

In [79]:
print(b)
b.ndim  # Number of array dimensions

[[1.5 2.  3. ]
 [4.  5.  6. ]]


2

In [80]:
print(e)
e.size  # Number of array elements

[[7 7]
 [7 7]]


4

In [81]:
b.dtype  # Data type of array elements

dtype('float64')

In [82]:
b.dtype.name  # Name of data type

'float64'

In [83]:
b.astype(int)  # Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

## Array Mathematics

### Arithmetic Ops

There is a feature of numpy called **broadcasting**. It allows mathematical array operations to be performed very quickly (in C instead of Python)

It is done using four rules:

* All input arrays with ndim smaller than the input array of largest ndim, have 1’s prepended to their shapes.

* The size in each dimension of the output shape is the maximum of all the input sizes in that dimension.

* An input can be used in the calculation if its size in a particular dimension either matches the output size in that dimension, or has value exactly 1.

Let's see it in action using the two arrays defined below

In [87]:
a = np.array([1, 2, 3])
b = np.array([[1.5, 2.,  3.], [4.,  5.,  6.]])
print_a(a)
print_a(b)

Shape: (3,)
[1 2 3]
Shape: (2, 3)
[[1.5 2.  3. ]
 [4.  5.  6. ]]


#### Subtraction and Addition

We can see that the dimension mismatch error doesn't happen b/c array a is broadcast to each from in b

In [88]:
g = a - b
print('Subtraction\n a - b = g\n\n {}\n - \n{}\n =\n{}'.format(a, b, g))

Subtraction
 a - b = g

 [1 2 3]
 - 
[[1.5 2.  3. ]
 [4.  5.  6. ]]
 =
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [90]:
np.subtract(a, b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [91]:
h = b + a
print('Addition\n a + b = h\n\n {}\n + \n{}\n =\n{}'.format(a, b, h))

Addition
 a + b = h

 [1 2 3]
 + 
[[1.5 2.  3. ]
 [4.  5.  6. ]]
 =
[[2.5 4.  6. ]
 [5.  7.  9. ]]


In [93]:
np.add(b, a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

#### Division and Multiplication

In [94]:
i = a / b
print('Division\n a / b = h\n\n {}\n / \n{}\n =\n{}'.format(a, b, i))

Division
 a / b = h

 [1 2 3]
 / 
[[1.5 2.  3. ]
 [4.  5.  6. ]]
 =
[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]


In [95]:
np.divide(a, b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

1:12: E231 missing whitespace after ','


In [96]:
j = a * b
print('Multiplication\n a * b = h\n\n {}\n * \n{}\n =\n{}'.format(a, b, j))

Multiplication
 a * b = h

 [1 2 3]
 * 
[[1.5 2.  3. ]
 [4.  5.  6. ]]
 =
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]


In [97]:
np.multiply(a, b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

#### Other Mathy Stuff

Exponentiation, square roots, sin, cos, etc

In [98]:
print(b)
np.exp(b)  # Exponentiation (ie. e^b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [99]:
print(b)
np.sqrt(b)  # Square root

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [100]:
print(a)
np.sin(a)  # Print sines of an array

[1 2 3]


array([0.84147098, 0.90929743, 0.14112001])

In [101]:
print(b)
np.cos(b)  # Element-wise cosine

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [102]:
print(a)
np.log(a)  # Element-wise natural logarithm

[1 2 3]


array([0.        , 0.69314718, 1.09861229])

### Comparison (element-wise and array-wise)

```python
array_1 == array_2  # element-wise comp
np.array_equal()  # test if same shape, same elements values
np.array_equiv()  # test if broadcastable shape, same elements values
np.allclose() # test if same shape, elements have close enough values
```

In [106]:
print_a(a)
a < 2  # Element-wise comparison array([True, False, False], dtype=bool)

Shape: (3,)
[1 2 3]


array([ True, False, False])

In [105]:
print_a(a)
print_a(b)
a == b  # Element-wise comparison

Shape: (3,)
[1 2 3]
Shape: (2, 3)
[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[False,  True,  True],
       [False, False, False]])

In [116]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

In [115]:
print(np.array_equal(a, b))
print(np.array_equiv(a, b))
print(np.allclose(a, b))

True
True
True


In [125]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [1, 2, 3]])

In [126]:
print(np.array_equal(a, b))
print(np.array_equiv(a, b))
print(np.allclose(a, b))

False
True
True


In [129]:
a = np.array([1e10, 1e-8])
b = np.array([1.00001e10, 1e-9])

In [131]:
print(np.array_equal(a, b))
print(np.array_equiv(a, b))
print(np.allclose(a, b))

False
False
True


### Aggregate Functions

```python
my_array.sum()
my_array.min()
my_array.max()
my_array.cumsum()
my_array.median()
my_array.mean()
my_array.std()
```

In [137]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [134]:
a.sum()  # Array-wise sum

6

In [135]:
print('{}\n'.format(a))

print(a.min())  # Array-wise minimum value
print(a.max())  # Array-wise maximum value

[1 2 3]

1
3


In [138]:
b[0][2] = 0
b[1][1] = 1
print('{}\n'.format(b))

print(b.min(axis=0))  # Minimum value of an array row (min along axis)
print(b.max(axis=0))  # Maximum value of an array row (max along axis)

[[1 2 0]
 [4 1 6]]

[1 1 0]
[4 2 6]


In [139]:
print('{}\n'.format(b))

print(b.min(axis=1))  # Minimum value of an array row (min along axis)
print(b.max(axis=1))  # Maximum value of an array row (max along axis)

[[1 2 0]
 [4 1 6]]

[0 1]
[2 6]


In [140]:
print('{}\n'.format(b))
b.cumsum(axis=1)  # Cumulative sum of the elements

[[1 2 0]
 [4 1 6]]



array([[ 1,  3,  3],
       [ 4,  5, 11]])

In [141]:
print('{}\n'.format(a))
a.mean()  # Mean

[1 2 3]



2.0

In [142]:
print('{}\n'.format(b))
np.median(b)  # Median

[[1 2 0]
 [4 1 6]]



1.5

In [143]:
print('{}\n'.format(a))
np.corrcoef(a)  # Correlation coefficient

[1 2 3]



1.0

In [144]:
print('{}\n'.format(b))
np.std(b)  # Standard deviation

[[1 2 0]
 [4 1 6]]



2.0548046676563256

## Copying

```python
my_array.view()
my_array.copy()
```

**COPY / DEEP COPY:** When the contents are physically stored in another location, it is called Copy (deep by default). 

**VIEW / SHALLOW COPY:** If on the other hand, a different view of the same memory content is provided, we call it as View.

In [145]:
print('Array: {} --> mem loc: {}\n'.format(a, a.__array_interface__['data']))

h = a.view()  # Create a view of the array with the same data

print('Array: {} --> mem loc: {}\n'.format(h, h.__array_interface__['data']))

Array: [1 2 3] --> mem loc: (140190773552048, False)

Array: [1 2 3] --> mem loc: (140190773552048, False)



In [149]:
print('Array: {} --> mem loc: {}\n'.format(a, a.__array_interface__['data']))

h = np.copy(a)  # Create a copy of the array

print('Array: {} --> mem loc: {}\n'.format(h, h.__array_interface__['data']))

Array: [1 2 3] --> mem loc: (140190773552048, False)

Array: [1 2 3] --> mem loc: (140190773429392, False)



In [148]:
print('Array: {} --> mem loc: {}\n'.format(a, a.__array_interface__['data']))

i = a.copy()  # Create a copy of the array

print('Array: {} --> mem loc: {}\n'.format(h, h.__array_interface__['data']))

Array: [1 2 3] --> mem loc: (140190773552048, False)

Array: [1 2 3] --> mem loc: (140190773577344, False)



## Sorting

```python
my_array.sort()
```

In [152]:
a = np.array([2, 1, 4])
print(a)

a.sort()  # Sort an array in place
print(a)

[2 1 4]
[1 2 4]


In [154]:
c = np.random.randint(0, 9, (2, 2, 3))
print('{}\n\n'.format(c))

c.sort(axis=0)  # Sort the elements of an array's axis
print(c)

[[[1 3 1]
  [3 2 0]]

 [[1 7 7]
  [2 5 2]]]


[[[1 3 1]
  [2 2 0]]

 [[1 7 7]
  [3 5 2]]]


## Subsetting, Slicing, Indexing

```python
my_array[2]
my_array[0][1]
my_array[0, 1] 
my_array[0:2, 1]
my_array[0:2, ...]
```

**Subsetting** - selecting specific rows and columns within the data

**Slicing** - selecting subsets based on a range of values

**Indexing** - selecting specific array values

In [4]:
a = np.array([1, 2, 4])
b = np.array([[1, 2, 0], [4, 1, 6]])
print_a(a)
print_a(b)

Shape: (3,)
[1 2 4]
Shape: (2, 3)
[[1 2 0]
 [4 1 6]]


In [188]:
a[2]  # Select the element at the 2nd index

4

In [190]:
b[0][1]  # Select the 0th element then the 1st element of the 0th

2

In [14]:
a[a < 2]  # Select elements less than 2

array([1])

In [16]:
b[[1, 0, 1, 0], [0, 1, 2, 0]]  # Select elements (1,0),(0,1),(1,2) and (0,0)

array([4, 2, 6, 1])

In [20]:
b[0, 1]  # Select 0th item in first dim, 1st item in second dim

2

In [6]:
a[0:2]  # Select items between indices 0 and 2

array([1, 2])

In [7]:
b[0:2, 1]  # Select items at rows 0 and 1 in column 1

array([2, 1])

In [182]:
b[:1]  # Select all items at row 0

array([[1, 2, 0]])

In [8]:
b[0:1, :] # Select all items at row 0

array([[1, 2, 0]])

In [10]:
b[1, ...]  # Same as [1,:,:]

array([4, 1, 6])

In [23]:
# Try predicting the output of this one on your own
b[[1, 0, 1, 0]][:, [0, 1, 2, 0]]

array([[4, 1, 6, 4],
       [1, 2, 0, 1],
       [4, 1, 6, 4],
       [1, 2, 0, 1]])

## Array Manipulation

In [63]:
a = np.array([1, 2, 4])
b = np.array([[1, 2, 0], [4, 1, 6]])

c = np.array([[1], [2], [3]])
d = np.array([[[0], [0], [0]], [[0], [0], [0]]])

### Changing Array Shape

```python
np.transpose()
my_array.ravel()
my_array.flatten()
my_array.reshape()
```

In [28]:
i = np.transpose(b)
i

array([[1, 4],
       [2, 1],
       [0, 6]])

In [30]:
i.T  # alternative to writing out transpose

array([[1, 2, 0],
       [4, 1, 6]])

In [31]:
b.ravel()  # flatten out an array
# b.flatten() # alternative to ravel

array([1, 2, 0, 4, 1, 6])

In [36]:
b.reshape(3, -2)  # reshape an array

array([[1, 2],
       [0, 4],
       [1, 6]])

### Adding/Removing Elements

```python
my_array.append()
my_array.insert()
my_array.delete()
```

In [ ]:
h.resize((2,6)) Return a new array with shape (2,6)
>>> np.append(h,g) Append items to an array
>>> np.insert(a, 1, 5) Insert items in an array
>>> np.delete(a,[1]) Delete items from an array

### Combining Arrays

```python
np.concatenate()
np.vstack()
np.hstack()
np.column_stack()
np.row_stack()
```

In [64]:
print(a.shape)
np.concatenate((a, a), axis=0)  # Concatenate arrays

array([1, 2, 4, 1, 2, 4])

In [61]:
np.concatenate((c, d))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

Stack arrays vertically (row-wise)

In [53]:
np.vstack((a, b))

array([[1, 2, 4],
       [1, 2, 0],
       [4, 1, 6]])

In [52]:
np.vstack((c, d))

array([[1],
       [2],
       [3],
       [0],
       [0],
       [0]])

Stack arrays horizontally (column-wise)

In [56]:
np.hstack((c, d))

array([[1, 0],
       [2, 0],
       [3, 0]])

In [ ]:
np.row_stack

In [50]:
np.column_stack((c, d))  # Create stacked column-wise arrays

array([[1, 0],
       [2, 0],
       [3, 0]])

In [ ]:
>>> np.vstack(([1,2,3],[4,5,6]))
array([[1, 2, 3],
       [4, 5, 6]])
>>> np.column_stack(([1,2,3],[4,5,6]))
array([[1, 4],
       [2, 5],
       [3, 6]])
>>> np.hstack(([1,2,3],[4,5,6]))
array([1, 2, 3, 4, 5, 6])

### Splitting Arrays

```python
np.hsplit()
np.vsplit()
```

In [ ]:
np.hsplit(a,3) Split the array horizontally at the 3rd
 [array([1]),array([2]),array([3])] index
>>> np.vsplit(c,2) Split the array vertically at the 2nd index
[array([[[ 1.5, 2. , 1. ],
 [ 4. , 5. , 6. ]]]),
 array([[[ 3., 2., 3.],
 [ 4., 5., 6.]]])]

# Exercises

### Exercise #1

Create a numpy array of tuples with dates from 2019-2030 in the first position followed by 6 random numbers. Do this in the most efficient way.

```python
date_to_create = [('2019-01-01', 100.  , 104.06,  95.96, 100.34, 22351900, 100.34)
                  ('2020-01-01', 101.01, 109.08, 100.5 , 108.31, 11428600, 108.31)
                  ('2021-01-01', 110.75, 113.48, 109.05, 109.4 ,  9137200, 109.4 )
                  ...
                  ('2028-01-01', 313.16, 341.89, 310.3 , 332.  , 10597800, 332.  )
                  ('2029-01-01', 355.79, 381.95, 345.75, 381.02,  8905500, 381.02)
                  ('2030-01-01', 393.53, 394.5 , 357.  , 362.71,  7784800, 362.71)]
```

### Exercise #2

Create a numpy array ...

In [ ]:
# Complete the exercise here

# Answers